version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

  dotnet:
    build: .
    ports:
      - 7878:8080
    env_file:
      - .env
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
