name: Build and Test
on:
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'
  SERVICE_NAME: 'bottle-splitter'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build
        run:  dotnet run --project build/build.csproj
